spring.application.name=support_app
server.port=8081

// *# Core
// spring.profiles.active=devh2

// #base end-points config
// api-endpoint = api/v1

# Conexión MySQL Docker
spring.datasource.url=jdbc:mysql://localhost:3306/support_db
spring.datasource.username=support_user
spring.datasource.password=support_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Prefijo API
api-endpoint=api/v1